version: 0.2
phases:
  pre_build:
    commands:
      dotnet restore ./ExemploMVC/ExemploMVC.csproj
  build:
    commands:
      dotnet publish -c release -o ./ExemploMVC/build_output ./ExemploMVC/ExemploMVC.csproj

artifacts:
  files:
    - ./ExemploMVC/build_output/**/*
    - ./buildspec.yml